stages:
  - check
  - build
  - test

include:
  - component: $CI_SERVER_FQDN/eng/gitlab-templates/check-issue@~latest
    inputs:
      stage: check

  # gnatformat check
  - component: $CI_SERVER_FQDN/eng/gitlab-templates/gnatformat@main
    inputs:
      stage: check
      anod-spec: stable_sloc
      gnatformat-args: -P stable_sloc_cli.gpr --check
      install-gnatformat: true
      install-gnatformat-extra-anod-args: "-Qrelease=26.0"

  # Pre-commit check. Skip gnatformat as it is taken care of by the gnatformat
  # job.
  - component: $CI_SERVER_FQDN/eng/gitlab-templates/pre-commit@~latest
    inputs:
      pre-commit-skip: "gnatformat"

  - component: $CI_SERVER_FQDN/eng/gitlab-templates/build@~latest
    inputs:
      stage: build
      anod-args: build stable_sloc
      save-component: true
      linux: true
      cpus: 8
      disk: 80
      windows: true
      windows-cpus: 2
      windows-mem: 4

  - component: $CI_SERVER_FQDN/eng/gitlab-templates/test@~latest
    inputs:
      stage: test
      anod-args: test stable_sloc
      linux: true
      cpus: 8
      disk: 80
      windows: true
      windows-cpus: 2
      windows-mem: 4
